import Link from 'next/link';

import styles from './layout.module.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};

const SIDE_MENUS = [
  { name: 'ホーム', path: '/' },
  { name: '記事一覧', path: '/articles' },
  { name: 'お気に入り', path: '/articles/likes' },
  { name: 'プロフィール', path: '/articles/profile' },
  // { name: '設定', path: '/articles/setting' },
] as const;

export default function Layout({ children }: Props) {
  return (
    <div className={styles.root}>
      <aside className={styles.sidebar}>
        <nav>
          <ul>
            {SIDE_MENUS.map((sideMenu) => (
              <li key={sideMenu.name} className={styles.sidebar__item}>
                <Link href={sideMenu.path}>{sideMenu.name}</Link>
              </li>
            ))}
          </ul>
        </nav>
      </aside>
      <main className={styles.main}>{children}</main>
    </div>
  );
}
