import { SideMenu } from './components/SideMenu/SideMenu';
import styles from './layout.module.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};

export default function Layout({ children }: Props) {
  return (
    <div className={styles.root}>
      <SideMenu />
      <main className={styles.main}>{children}</main>
    </div>
  );
}
