import Link from 'next/link';

import styles from './layout.module.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};

const getSideMenus = (userId: string) => {
  return [
    { name: 'ホーム', path: '/' },
    { name: '記事一覧', path: '/blog/articles' },
    { name: 'お気に入り', path: '/blog/articles/likes' },
    { name: 'プロフィール', path: `/blog/${userId}` },
    // { name: '設定', path: '/blog/setting' },
  ] as const;
};

export default function Layout({ children }: Props) {
  const sideMenu = getSideMenus('1');
  return (
    <div className={styles.root}>
      <aside className={styles.sidebar}>
        <nav>
          <ul>
            {sideMenu.map((sideMenu) => (
              <li key={sideMenu.name} className={styles.sidebar__item}>
                <Link href={sideMenu.path}>{sideMenu.name}</Link>
              </li>
            ))}
          </ul>
        </nav>
      </aside>
      <main className={styles.main}>{children}</main>
    </div>
  );
}
